### ISSUE TITLE
参数设置：

### ISSUE THREAD

**Issue by JHFSUE** [lucky7-code/DKVMN#1]
你好，假设有27个不同的问题，每个样本回答了50个问题，代码的参数
--length
--questions    
--final_fc_dim        
--question_dim        
--question_and_answer_dim
--memory_size
设置为多少

**Comment by lucky7-code** [comment]
length 50
questions 27
其他为超参

**Comment by Wangzc153** [comment]
大佬你好，我有这个错误提示可以告知如何解决吗？
Traceback (most recent call last):
  File "E:\Desktop\DKVMN-main\DKVMN-main\evaluation\run.py", line 29, in <module>
    from ..data.dataloader import getDataLoader
ImportError: attempted relative import with no known parent package

**Comment by JHFSUE** [comment]
您好，在pycharm中右击DKVMN-main-pytorch文件夹，点击一下Sources Root，希望能够解决你的问题。



&nbsp;


飒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 晚上9:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lucky7-code/DKVMN] 参数设置： (Issue #1)





 
大佬你好，我有这个错误提示可以告知如何解决吗？
 Traceback (most recent call last):
 File "E:\Desktop\DKVMN-main\DKVMN-main\evaluation\run.py", line 29, in 
 from ..data.dataloader import getDataLoader
 ImportError: attempted relative import with no known parent package
